apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: MyApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: hossamesaaa/pipeline
        image: hossamesaaa/pipeline
        ports:
        - containerPort: 80
